-- CreateTable
CREATE TABLE "public"."orders" (
    "id" INTEGER NOT NULL,
    "number" TEXT,
    "status_id" INTEGER,
    "status_name" TEXT,
    "status_overdue" BOOLEAN,
    "created_at" TIMESTAMP(3),
    "created_by_id" INTEGER,
    "modified_at" TIMESTAMP(3),
    "done_at" TIMESTAMP(3),
    "closed_at" TIMESTAMP(3),
    "closed_by_id" INTEGER,
    "branch_id" INTEGER,
    "order_type_id" INTEGER,
    "order_type_name" TEXT,
    "manager_id" INTEGER,
    "assignee_id" INTEGER,
    "asset_id" INTEGER,
    "asset_uid" TEXT,
    "asset_brand" TEXT,
    "asset_model" TEXT,
    "asset_year" TEXT,
    "client_id" INTEGER,
    "client_name" TEXT,
    "client_is_organization" BOOLEAN,
    "payer_id" INTEGER,
    "payer_name" TEXT,
    "scheduled_for" TIMESTAMP(3),
    "scheduled_to" TIMESTAMP(3),
    "resource_id" INTEGER,
    "resource_name" TEXT,
    "malfunction" TEXT,
    "manager_notes" TEXT,
    "engineer_notes" TEXT,
    "address" TEXT,
    "resume" TEXT,
    "estimated_price" DOUBLE PRECISION,
    "due_date" TIMESTAMP(3),
    "overdue" BOOLEAN,
    "discount_sum" DOUBLE PRECISION,
    "payed" DOUBLE PRECISION,
    "total" DOUBLE PRECISION,
    "warranty_date" TIMESTAMP(3),
    "urgent" BOOLEAN,
    "is_deduction_required" BOOLEAN,
    "ad_campaign_id" INTEGER,
    "custom_fields" TEXT,
    "asset_custom_fields" TEXT,
    "client_custom_fields" TEXT,

    CONSTRAINT "orders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."order_items" (
    "order_id" INTEGER NOT NULL,
    "id" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3),
    "assignee_id" INTEGER,
    "entity_id" INTEGER,
    "entity_type" TEXT,
    "entity_title" TEXT,
    "entity_code" TEXT,
    "entity_sku" TEXT,
    "entity_description" TEXT,
    "entity_sn_accounting" BOOLEAN,
    "entity_is_hidden" BOOLEAN,
    "uom_id" INTEGER,
    "uom_title" TEXT,
    "uom_description" TEXT,
    "quantity" DOUBLE PRECISION,
    "price" DOUBLE PRECISION,
    "cost" DOUBLE PRECISION,
    "margin_id" INTEGER,
    "is_deduction_required" BOOLEAN,
    "is_refunded" BOOLEAN,
    "comment" TEXT,
    "comment_visibility" INTEGER,
    "discount_type" TEXT,
    "discount_percentage" DOUBLE PRECISION,
    "discount_amount" DOUBLE PRECISION,
    "discount_sponsor" TEXT,
    "warranty_period" INTEGER,
    "warranty_period_units" TEXT,
    "expiration_date" TIMESTAMP(3),
    "taxes" TEXT,
    "write_offs" TEXT,

    CONSTRAINT "order_items_pkey" PRIMARY KEY ("order_id","id")
);

-- CreateIndex
CREATE INDEX "orders_modified_at_idx" ON "public"."orders"("modified_at");
